FROM postgres:10.0-alpine

# PGXS depenencies
RUN apk --update add make diffutils git

RUN mkdir /install && \
    cd /install && \
    git clone https://github.com/m-martinez/pg-audit-json.git && \
    cd pg-audit-json && \
    make && \
    make install

# Update config with non-durable settings (fsync,  synchronous_commit|full_page_writes)
# See: https://www.postgresql.org/docs/10.0/static/non-durability.html
RUN sed -ri "s!^#?(fsync|synchronous_commit|full_page_writes)\s*=\s*\S+.*!\1 = off!" /usr/local/share/postgresql/postgresql.conf.sample
